// Code generated by "stringer -type=JobType,QueueType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JobTypeCampaignCreation-1]
}

const _JobType_name = "JobTypeCampaignCreation"

var _JobType_index = [...]uint8{0, 23}

func (i JobType) String() string {
	i -= 1
	if i < 0 || i >= JobType(len(_JobType_index)-1) {
		return "JobType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _JobType_name[_JobType_index[i]:_JobType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueueTypeCampaignCreation-1]
}

const _QueueType_name = "QueueTypeCampaignCreation"

var _QueueType_index = [...]uint8{0, 25}

func (i QueueType) String() string {
	i -= 1
	if i < 0 || i >= QueueType(len(_QueueType_index)-1) {
		return "QueueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _QueueType_name[_QueueType_index[i]:_QueueType_index[i+1]]
}
